// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9n336oq3MGVldc2W7tIoNciP4kWrTJY',
    appId: '1:661889541971:web:58531d6aa9cb735f86e3a6',
    messagingSenderId: '661889541971',
    projectId: 'tryfferapp',
    authDomain: 'tryfferapp.firebaseapp.com',
    databaseURL: 'https://tryfferapp-default-rtdb.firebaseio.com',
    storageBucket: 'tryfferapp.appspot.com',
    measurementId: 'G-ENYZ609D9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAymCk3FNiHFrCEDUev3D4K4PQBXFxgTJk',
    appId: '1:661889541971:android:8aa48cab688688c986e3a6',
    messagingSenderId: '661889541971',
    projectId: 'tryfferapp',
    databaseURL: 'https://tryfferapp-default-rtdb.firebaseio.com',
    storageBucket: 'tryfferapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzrTjIL0akyWF_fIpTCxH9Gt1VHFPG96A',
    appId: '1:661889541971:ios:a5b6072e1bd7bb0d86e3a6',
    messagingSenderId: '661889541971',
    projectId: 'tryfferapp',
    databaseURL: 'https://tryfferapp-default-rtdb.firebaseio.com',
    storageBucket: 'tryfferapp.appspot.com',
    androidClientId: '661889541971-8q8culodpmtqjn8l4vmhd5pb6pg8l5nc.apps.googleusercontent.com',
    iosClientId: '661889541971-94g1h5r3ru2i1sd9umi7apgk8sh01cph.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketPlace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzrTjIL0akyWF_fIpTCxH9Gt1VHFPG96A',
    appId: '1:661889541971:ios:a8725d8792ea088a86e3a6',
    messagingSenderId: '661889541971',
    projectId: 'tryfferapp',
    databaseURL: 'https://tryfferapp-default-rtdb.firebaseio.com',
    storageBucket: 'tryfferapp.appspot.com',
    androidClientId: '661889541971-8q8culodpmtqjn8l4vmhd5pb6pg8l5nc.apps.googleusercontent.com',
    iosClientId: '661889541971-66sopjl5c1mdi657ai2s4vivfota0g6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketPlace.RunnerTests',
  );
}
